### PR TITLE
Logo

### PR DESCRIPTION
**Pull request by foways**
last result

concept

### CODE REVIEW

**Comment by sogatanco** [comment]
good job. But I want a logo that can be used directly on my application. can you provide it?

**Comment by foways** [comment]
### This logo is in .png format

rw logo 01
<hr>

rw logo 02
<hr>

rw logo 03
<hr>

rw logo 04
<hr>

### Size

100px
100px

200px
200px

300px
300px

### Mono Size 

32px
l 32px

64px
l 64px

**Comment by foways** [comment]
EDITABLE FILE : https://drive.google.com/drive/folders/1_qdtkgFsT3KFKx_uMD5eBiL2IIehwopa?usp=sharing

**Comment by sogatanco** [comment]
Thank a lot bro, i will use your design asap on my app

**Comment by sogatanco** [comment]
Thank a lot bro, i will use your design asap on my app

**Pull request merged**
